package gestiondeshopitauxbackend.ENUMS;

public enum SpecialiteMedecin {
    GENERALISTE,
    CARDIOLOGUE,
    DERMATOLOGUE,
    GASTROENTEROLOGUE,
    GYNECOLOGUE,
    NEUROLOGUE,
    ONCOLOGUE,
    OPHTALMOLOGUE,
    ORL,
    PEDIATRE,
    PSYCHIATRE,
    PNEUMOLOGUE,
    RADIOLOGUE,
    RHEUMATOLOGUE,
    UROLOGUE,
    ENDOCRINOLOGUE,
    NEPHROLOGUE,
    MEDECIN_URGENTISTE,
    ANESTHESISTE
}
